package com.fincontrol.model;

import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Categoria")
public class Categoria {
	private UUID codCategoria;
	private String descricao;
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="codCategoria")
	public UUID getCodCategoria() {
		return codCategoria;
	}
	public void setCodCategoria(UUID codCategoria) {
		this.codCategoria = codCategoria;
	}
	@DynamoDBAttribute(attributeName="descricao")
	public String getDescricao() {
		return descricao;
	}
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
	@Override
	public String toString() {
		return "Categoria: {codCategoria: " + codCategoria + ", descricao: " + descricao + " }";
	}
}
